# Generated by Django 5.2.3 on 2025-12-01 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название курса', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание курса', verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание курса', max_length=350, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, help_text='Обложка курса', null=True, upload_to='courses/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Уникальный slug курса', unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена курса (0 = бесплатно)', max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('web', 'Веб-разработка'), ('data-science', 'Data Science'), ('other', 'Другое')], default='python', help_text='Категория курса', max_length=50, verbose_name='Категория')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, help_text='Рейтинг курса (0-5)', max_digits=3, verbose_name='Рейтинг')),
                ('is_featured', models.BooleanField(default=False, help_text="Отображать как 'Хит' или 'Новый'", verbose_name='Избранный')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания курса', verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления курса', verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'), models.Index(fields=['-created_at'], name='courses_cou_created_c141ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название урока', max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Уникальный slug урока', unique=True, verbose_name='Slug')),
                ('lesson_number', models.PositiveIntegerField(default=1, help_text='Порядковый номер урока в курсе', verbose_name='№ урока')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание урока', max_length=350, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, help_text='Обложка урока', null=True, upload_to='lessons/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания урока', verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления урока', verbose_name='Обновлен')),
                ('course', models.ForeignKey(help_text='Курс', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='LessonSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_url', models.URLField(verbose_name='Ссылка на работу')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('in_review', 'На проверке'), ('changes_requested', 'Требуются доработки'), ('approved', 'Одобрено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('mentor_comment', models.TextField(blank=True, help_text='Комментарий для студента о необходимых правках (поддерживает Markdown)', verbose_name='Комментарий ментора')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Когда ментор проверил работу', null=True, verbose_name='Дата проверки')),
                ('revision_count', models.IntegerField(default=0, help_text='Сколько раз работа отправлялась на доработку', verbose_name='Попытка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.lesson', verbose_name='Урок')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='authentication.student', verbose_name='Ментор')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_submissions', to='authentication.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Работа студента',
                'verbose_name_plural': 'Работы студентов',
            },
        ),
        migrations.CreateModel(
            name='ImprovementStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое описание того, что нужно исправить', max_length=300, verbose_name='Название шага')),
                ('description', models.TextField(help_text='Подробная инструкция для студента (поддерживает Markdown)', verbose_name='Описание')),
                ('order', models.IntegerField(default=0, help_text='Порядковый номер шага', verbose_name='Порядок')),
                ('is_completed', models.BooleanField(default=False, help_text='Студент отметил шаг как выполненный', verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_steps_list', to='courses.lessonsubmission', verbose_name='Работа студента')),
            ],
            options={
                'verbose_name': 'Шаг доработки',
                'verbose_name_plural': 'Шаги доработки',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название шага', max_length=200, verbose_name='Название')),
                ('step_number', models.PositiveIntegerField(default=1, help_text='Порядковый номер шага в уроке', verbose_name='№ шага')),
                ('description', models.TextField(blank=True, help_text='Описание шага', verbose_name='Описание')),
                ('actions', models.TextField(blank=True, help_text='Действия шага', verbose_name='Действия')),
                ('self_check', models.TextField(blank=True, help_text='Проверка себя', verbose_name='Проверка себя')),
                ('repair_description', models.CharField(blank=True, help_text='Описание ремонта', max_length=200, verbose_name='Описание ремонта')),
                ('image', models.ImageField(blank=True, help_text='Изображение шага', null=True, upload_to='steps/', verbose_name='Изображение')),
                ('lesson', models.ForeignKey(help_text='Урок', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Шаг урока',
                'verbose_name_plural': 'Шаги урока',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ExtraSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название источника', max_length=200, verbose_name='Название')),
                ('url', models.URLField(blank=True, help_text='Ссылка на источник', verbose_name='Ссылка')),
                ('steps', models.ManyToManyField(blank=True, help_text='Шаги, к которым относится источник', related_name='extra_sources', to='courses.step', verbose_name='Шаги')),
            ],
            options={
                'verbose_name': 'Дополнительный источник',
                'verbose_name_plural': 'Дополнительные источники',
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='authentication.student')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.step')),
            ],
            options={
                'verbose_name': 'Прогресс по шагу',
                'verbose_name_plural': 'Прогресс по шагам',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Заголовок совета', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание совета', verbose_name='Описание')),
                ('step', models.ForeignKey(help_text='Шаг урока', on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='courses.step', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course'], name='courses_les_course__c1b0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_number'], name='courses_les_lesson__b8f0b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'lesson_number'), name='unique_lesson_number_per_course'),
        ),
        migrations.AddIndex(
            model_name='lessonsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='courses_les_status_07b77b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsubmission',
            index=models.Index(fields=['mentor', 'status'], name='courses_les_mentor__7b73b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonsubmission',
            unique_together={('student', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='improvementstep',
            index=models.Index(fields=['submission', 'order'], name='courses_imp_submiss_2e0d00_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['lesson'], name='courses_ste_lesson__f391d4_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['step_number'], name='courses_ste_step_nu_d3aa99_idx'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('lesson', 'step_number'), name='unique_step_number_per_lesson'),
        ),
        migrations.AddIndex(
            model_name='extrasource',
            index=models.Index(fields=['name'], name='courses_ext_name_866158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stepprogress',
            unique_together={('profile', 'step')},
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['step'], name='courses_tip_step_id_6cf6c4_idx'),
        ),
    ]
