# Generated by Django 5.2.3 on 2025-12-18 08:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название курса", max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание курса", verbose_name="Описание"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Краткое описание курса",
                        max_length=350,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Обложка курса",
                        null=True,
                        upload_to="courses/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный slug курса", unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Цена курса (0 = бесплатно)",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("web", "Веб-разработка"),
                            ("data-science", "Data Science"),
                            ("other", "Другое"),
                        ],
                        default="python",
                        help_text="Категория курса",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        help_text="Рейтинг курса (0-5)",
                        max_digits=3,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Отображать как 'Хит' или 'Новый'",
                        verbose_name="Избранный",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("draft", "Черновик"),
                            ("archived", "Архив"),
                            ("coming_soon", "Скоро"),
                        ],
                        default="active",
                        help_text="Статус курса",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания курса", verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата последнего обновления курса",
                        verbose_name="Обновлен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="courses_cou_name_eb4cc3_idx"),
                    models.Index(fields=["-created_at"], name="courses_cou_created_c141ec_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название урока", max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный slug урока", unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "lesson_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Порядковый номер урока в курсе",
                        verbose_name="№ урока",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Краткое описание урока",
                        max_length=350,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Обложка урока",
                        null=True,
                        upload_to="lessons/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания урока", verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата последнего обновления урока",
                        verbose_name="Обновлен",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["lesson_number"],
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название шага", max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "step_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Порядковый номер шага в уроке", verbose_name="№ шага"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание шага", verbose_name="Описание"
                    ),
                ),
                (
                    "actions",
                    models.TextField(
                        blank=True, help_text="Действия шага", verbose_name="Действия"
                    ),
                ),
                (
                    "self_check",
                    models.TextField(
                        blank=True, help_text="Проверка себя", verbose_name="Проверка себя"
                    ),
                ),
                (
                    "repair_description",
                    models.CharField(
                        blank=True,
                        help_text="Описание ремонта",
                        max_length=200,
                        verbose_name="Описание ремонта",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение шага",
                        null=True,
                        upload_to="steps/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="courses.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг урока",
                "verbose_name_plural": "Шаги урока",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="ExtraSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название источника", max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Ссылка на источник", verbose_name="Ссылка"
                    ),
                ),
                (
                    "steps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Шаги, к которым относится источник",
                        related_name="extra_sources",
                        to="courses.step",
                        verbose_name="Шаги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительный источник",
                "verbose_name_plural": "Дополнительные источники",
            },
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок совета", max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Описание совета", verbose_name="Описание"),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="Шаг урока",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="courses.step",
                        verbose_name="Шаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Совет",
                "verbose_name_plural": "Советы",
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["course"], name="courses_les_course__c1b0bb_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["lesson_number"], name="courses_les_lesson__b8f0b1_idx"),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("course", "lesson_number"), name="unique_lesson_number_per_course"
            ),
        ),
        migrations.AddIndex(
            model_name="step",
            index=models.Index(fields=["lesson"], name="courses_ste_lesson__f391d4_idx"),
        ),
        migrations.AddIndex(
            model_name="step",
            index=models.Index(fields=["step_number"], name="courses_ste_step_nu_d3aa99_idx"),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.UniqueConstraint(
                fields=("lesson", "step_number"), name="unique_step_number_per_lesson"
            ),
        ),
        migrations.AddIndex(
            model_name="extrasource",
            index=models.Index(fields=["name"], name="courses_ext_name_866158_idx"),
        ),
        migrations.AddIndex(
            model_name="tip",
            index=models.Index(fields=["step"], name="courses_tip_step_id_6cf6c4_idx"),
        ),
    ]
