# Generated by Django 5.2.3 on 2025-12-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonsubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonsubmission',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonsubmission',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='lessonsubmission',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='stepprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stepprogress',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='stepprogress',
            name='step',
        ),
        migrations.DeleteModel(
            name='ImprovementStep',
        ),
    ]
