# Generated by Django 5.2.3 on 2026-01-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Описание курса", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ka",
            field=models.TextField(
                blank=True, help_text="Описание курса", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ru",
            field=models.TextField(
                blank=True, help_text="Описание курса", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="name_en",
            field=models.CharField(
                help_text="Название курса", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="name_ka",
            field=models.CharField(
                help_text="Название курса", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="name_ru",
            field=models.CharField(
                help_text="Название курса", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="short_description_en",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание курса",
                max_length=350,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="short_description_ka",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание курса",
                max_length=350,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="short_description_ru",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание курса",
                max_length=350,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="extrasource",
            name="name_en",
            field=models.CharField(
                help_text="Название источника", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="extrasource",
            name="name_ka",
            field=models.CharField(
                help_text="Название источника", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="extrasource",
            name="name_ru",
            field=models.CharField(
                help_text="Название источника", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="extrasource",
            name="url_en",
            field=models.URLField(
                blank=True, help_text="Ссылка на источник", null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AddField(
            model_name="extrasource",
            name="url_ka",
            field=models.URLField(
                blank=True, help_text="Ссылка на источник", null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AddField(
            model_name="extrasource",
            name="url_ru",
            field=models.URLField(
                blank=True, help_text="Ссылка на источник", null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name_en",
            field=models.CharField(
                help_text="Название урока", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name_ka",
            field=models.CharField(
                help_text="Название урока", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name_ru",
            field=models.CharField(
                help_text="Название урока", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="short_description_en",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание урока",
                max_length=350,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="short_description_ka",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание урока",
                max_length=350,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="short_description_ru",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание урока",
                max_length=350,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="actions_en",
            field=models.TextField(
                blank=True, help_text="Действия шага", null=True, verbose_name="Действия"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="actions_ka",
            field=models.TextField(
                blank=True, help_text="Действия шага", null=True, verbose_name="Действия"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="actions_ru",
            field=models.TextField(
                blank=True, help_text="Действия шага", null=True, verbose_name="Действия"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Описание шага", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="description_ka",
            field=models.TextField(
                blank=True, help_text="Описание шага", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="description_ru",
            field=models.TextField(
                blank=True, help_text="Описание шага", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="name_en",
            field=models.CharField(
                help_text="Название шага", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="name_ka",
            field=models.CharField(
                help_text="Название шага", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="name_ru",
            field=models.CharField(
                help_text="Название шага", max_length=200, null=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="repair_description_en",
            field=models.CharField(
                blank=True,
                help_text="Описание ремонта",
                max_length=200,
                null=True,
                verbose_name="Описание ремонта",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="repair_description_ka",
            field=models.CharField(
                blank=True,
                help_text="Описание ремонта",
                max_length=200,
                null=True,
                verbose_name="Описание ремонта",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="repair_description_ru",
            field=models.CharField(
                blank=True,
                help_text="Описание ремонта",
                max_length=200,
                null=True,
                verbose_name="Описание ремонта",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="self_check_en",
            field=models.TextField(
                blank=True, help_text="Проверка себя", null=True, verbose_name="Проверка себя"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="self_check_ka",
            field=models.TextField(
                blank=True, help_text="Проверка себя", null=True, verbose_name="Проверка себя"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="self_check_ru",
            field=models.TextField(
                blank=True, help_text="Проверка себя", null=True, verbose_name="Проверка себя"
            ),
        ),
        migrations.AddField(
            model_name="tip",
            name="description_en",
            field=models.TextField(help_text="Описание совета", null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="tip",
            name="description_ka",
            field=models.TextField(help_text="Описание совета", null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="tip",
            name="description_ru",
            field=models.TextField(help_text="Описание совета", null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="tip",
            name="title_en",
            field=models.CharField(
                help_text="Заголовок совета", max_length=200, null=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="tip",
            name="title_ka",
            field=models.CharField(
                help_text="Заголовок совета", max_length=200, null=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="tip",
            name="title_ru",
            field=models.CharField(
                help_text="Заголовок совета", max_length=200, null=True, verbose_name="Заголовок"
            ),
        ),
    ]
