# Generated by Django 5.2.3 on 2026-01-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_description_en_course_description_ka_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="self_check_items",
            field=models.JSONField(
                blank=True,
                help_text="Список чекбоксов для самопроверки (JSON массив строк)",
                null=True,
                verbose_name="Чекбоксы самопроверки",
            ),
        ),
    ]
