# Generated by Django 5.2.3 on 2025-12-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lessonsubmission_unique_together_and_more'),
        ('reviewers', '0003_lessonsubmission_improvementstep_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonSubmission',
        ),
        migrations.DeleteModel(
            name='StepProgress',
        ),
    ]
