# Generated by Django 5.2.3 on 2025-12-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_lessonsubmission_delete_stepprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('draft', 'Черновик'), ('archived', 'Архив'), ('coming_soon', 'Скоро')], default='active', help_text='Статус курса', max_length=20, verbose_name='Статус'),
        ),
    ]
