# Generated by Django 5.2.3 on 2026-01-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_repair_description_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="troubleshooting_help",
            field=models.TextField(
                blank=True,
                help_text="Подсказки для студента при возникновении проблем (показывается студентам)",
                verbose_name="Помощь при трудностях",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="repair_description",
            field=models.TextField(
                blank=True,
                help_text="Примечания администратора при необходимости правок (НЕ показывается студентам)",
                verbose_name="Примечания администратора",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="repair_description_en",
            field=models.TextField(
                blank=True,
                help_text="Примечания администратора при необходимости правок (НЕ показывается студентам)",
                null=True,
                verbose_name="Примечания администратора",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="repair_description_ka",
            field=models.TextField(
                blank=True,
                help_text="Примечания администратора при необходимости правок (НЕ показывается студентам)",
                null=True,
                verbose_name="Примечания администратора",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="repair_description_ru",
            field=models.TextField(
                blank=True,
                help_text="Примечания администратора при необходимости правок (НЕ показывается студентам)",
                null=True,
                verbose_name="Примечания администратора",
            ),
        ),
    ]
