# Generated by Django 5.2.3 on 2026-01-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_add_troubleshooting_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="troubleshooting_help_en",
            field=models.TextField(
                blank=True,
                help_text="Подсказки для студента при возникновении проблем (показывается студентам)",
                null=True,
                verbose_name="Помощь при трудностях",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="troubleshooting_help_ka",
            field=models.TextField(
                blank=True,
                help_text="Подсказки для студента при возникновении проблем (показывается студентам)",
                null=True,
                verbose_name="Помощь при трудностях",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="troubleshooting_help_ru",
            field=models.TextField(
                blank=True,
                help_text="Подсказки для студента при возникновении проблем (показывается студентам)",
                null=True,
                verbose_name="Помощь при трудностях",
            ),
        ),
    ]
