# Generated by Django 5.2.3 on 2026-02-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_step_troubleshooting_help_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="self_check_items_en",
            field=models.JSONField(
                blank=True,
                help_text="Список чекбоксов для самопроверки (JSON массив строк)",
                null=True,
                verbose_name="Чекбоксы самопроверки",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="self_check_items_ka",
            field=models.JSONField(
                blank=True,
                help_text="Список чекбоксов для самопроверки (JSON массив строк)",
                null=True,
                verbose_name="Чекбоксы самопроверки",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="self_check_items_ru",
            field=models.JSONField(
                blank=True,
                help_text="Список чекбоксов для самопроверки (JSON массив строк)",
                null=True,
                verbose_name="Чекбоксы самопроверки",
            ),
        ),
    ]
