# Generated by Django 5.2.3 on 2026-03-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_newsletter_model"),
        ("courses", "0007_step_self_check_items_en_step_self_check_items_ka_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Статьи блога, связанные с этим шагом",
                related_name="course_steps",
                to="blog.article",
                verbose_name="Статьи",
            ),
        ),
    ]
