# Generated by Django 5.2.3 on 2026-01-30 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Дополнительные настройки подписки (частота, категории, etc.)",
                verbose_name="Настройки",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("blog", "📰 Блог - новые статьи"),
                    ("courses", "📚 Курсы - обновления и новые курсы"),
                    ("events", "🎉 События и вебинары"),
                    ("marketing", "🎁 Промо-акции и спецпредложения"),
                    ("system", "🔔 Системные уведомления"),
                    ("weekly_digest", "📊 Еженедельный дайджест"),
                ],
                default="blog",
                help_text="Категория контента для подписки",
                max_length=50,
                verbose_name="Тип подписки",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Связь с пользователем (null для анонимных подписок)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="email",
            field=models.EmailField(
                help_text="Email адрес для отправки уведомлений",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Активна ли подписка (для отписки без удаления)",
                verbose_name="Активна",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("email", "subscription_type")},
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["email", "subscription_type"], name="notificatio_email_0146ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "is_active"], name="notificatio_user_id_d6f425_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["subscription_type", "is_active"], name="notificatio_subscri_ed4dab_idx"
            ),
        ),
    ]
