# Generated by Django 5.2.3 on 2026-01-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_subscription_options_subscription_preferences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("email_notifications", "📧 Все email уведомления"),
                    ("course_updates", "📚 Обновления курсов"),
                    ("lesson_reminders", "⏰ Напоминания о уроках"),
                    ("achievement_alerts", "🏆 Уведомления о достижениях"),
                    ("weekly_summary", "📊 Еженедельная сводка"),
                    ("marketing_emails", "🎁 Маркетинговые письма"),
                ],
                default="email_notifications",
                help_text="Категория уведомлений (соответствует настройкам студента)",
                max_length=50,
                verbose_name="Тип подписки",
            ),
        ),
    ]
