# Markdownlint configuration for CLI2
# https://github.com/DavidAnson/markdownlint-cli2#configuration

config:
  default: true
  MD013: false  # Line length
  MD033: false  # Inline HTML
  MD041: false  # First line heading
  MD024:        # Duplicate headings
    siblings_only: true
  MD046: false  # Code block style
  MD029:        # Ordered list prefix
    style: "any"

globs:
  - "**/*.md"
  - "!src/**"
  - "!.venv/**"
  - "!node_modules/**"
