# Generated by Django 5.2.3 on 2026-01-29 19:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_step_troubleshooting_help_en_and_more"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для перенаправления на страницу оплаты",
                verbose_name="URL оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Стоимость курса в выбранной валюте",
                max_digits=12,
                verbose_name="Сумма платежа",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                help_text="Приобретаемый курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Время создания платежа", verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "Доллар США"),
                    ("GEL", "Грузинский лари"),
                    ("RUB", "Российский рубль"),
                ],
                default="USD",
                help_text="Валюта платежа",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                help_text="Ответы и данные от платежного шлюза",
                null=True,
                verbose_name="Дополнительные данные",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Уникальный идентификатор платежа",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Время успешного завершения платежа",
                null=True,
                verbose_name="Дата оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cloudpayments", "CloudPayments (РФ)"),
                    ("tbc_georgia", "TBC Bank (Грузия)"),
                ],
                help_text="Выбранная платежная система",
                max_length=20,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("processing", "Обрабатывается"),
                    ("completed", "Успешно завершён"),
                    ("failed", "Ошибка оплаты"),
                    ("cancelled", "Отменён"),
                    ("refunded", "Возвращён"),
                ],
                db_index=True,
                default="pending",
                help_text="Текущий статус транзакции",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Уникальный идентификатор транзакции от платежной системы",
                max_length=255,
                verbose_name="ID транзакции",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Время последнего обновления", verbose_name="Обновлено"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, совершающий покупку",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "-created_at"], name="payments_pa_user_id_7a85fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_pa_status_21ed42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"),
        ),
    ]
