# Generated by Django 5.2.3 on 2026-02-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_update_payment_methods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("bog", "BOG"), ("tbc", "TBC")],
                help_text="Выбранная платежная система",
                max_length=20,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
