# Generated by Django 5.2.3 on 2026-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_update_payment_method_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("bog", "BOG"), ("tbc", "TBC"), ("paddle", "Paddle")],
                help_text="Выбранная платежная система",
                max_length=20,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
