# Generated by Django 5.2.3 on 2025-12-18 08:28

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("lesson_url", models.URLField(verbose_name="Ссылка на работу")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает проверки"),
                            ("changes_requested", "Требуются доработки"),
                            ("approved", "Одобрено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "mentor_comment",
                    models.TextField(
                        blank=True,
                        help_text="Комментарий для студента о необходимых правках (поддерживает Markdown)",
                        verbose_name="Комментарий ментора",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда ментор проверил работу",
                        null=True,
                        verbose_name="Дата проверки",
                    ),
                ),
                (
                    "revision_count",
                    models.IntegerField(
                        default=0,
                        help_text="Сколько раз работа отправлялась на доработку",
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to="authentication.student",
                        verbose_name="Ментор",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_submissions",
                        to="authentication.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа студента",
                "verbose_name_plural": "Работы студентов",
                "db_table": "courses_lessonsubmission",
            },
        ),
        migrations.CreateModel(
            name="ImprovementStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Краткое описание того, что нужно исправить",
                        max_length=300,
                        verbose_name="Название шага",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Подробная инструкция для студента (поддерживает Markdown)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Порядковый номер шага", verbose_name="Порядок"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Студент отметил шаг как выполненный",
                        verbose_name="Выполнено",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_steps_list",
                        to="reviewers.lessonsubmission",
                        verbose_name="Работа студента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг доработки",
                "verbose_name_plural": "Шаги доработки",
                "db_table": "courses_improvementstep",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Принята"), ("needs_work", "Требуются доработки")],
                        default="approved",
                        max_length=20,
                        verbose_name="Статус проверки",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        help_text="Общие комментарии и рекомендации по работе",
                        verbose_name="Комментарии проверяющего",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Оценка от 1 до 5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка работы",
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Примерное время затраченное на проверку",
                        verbose_name="Время проверки (мин)",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее обновление"),
                ),
                (
                    "lesson_submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviewers.lessonsubmission",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="authentication.reviewer",
                        verbose_name="Проверяющий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецензия",
                "verbose_name_plural": "Рецензии",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewerNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_submission", "Новая работа на проверку"),
                            ("resubmission", "Повторная отправка работы"),
                            ("student_question", "Вопрос от студента"),
                            ("system", "Системное уведомление"),
                        ],
                        max_length=20,
                        verbose_name="Тип уведомления",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL для перехода к связанному объекту",
                        max_length=500,
                        verbose_name="Ссылка",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Прочитано")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authentication.reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление ревьюера",
                "verbose_name_plural": "Уведомления ревьюеров",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StepProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_progress",
                        to="authentication.student",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="courses.step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по шагу",
                "verbose_name_plural": "Прогресс по шагам",
                "db_table": "courses_stepprogress",
            },
        ),
        migrations.CreateModel(
            name="StudentImprovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "improvement_number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер улучшения"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Краткое название шага улучшения",
                        max_length=200,
                        verbose_name="Название улучшения",
                    ),
                ),
                (
                    "improvement_text",
                    models.TextField(
                        help_text="Что именно нужно исправить или улучшить",
                        verbose_name="Описание улучшения",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "Высокий"), ("medium", "Средний"), ("low", "Низкий")],
                        default="medium",
                        help_text="Важность данного улучшения",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Отметка студента о выполнении",
                        verbose_name="Выполнено",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда студент отметил как выполненное",
                        null=True,
                        verbose_name="Дата выполнения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "lesson_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvements",
                        to="reviewers.lessonsubmission",
                        verbose_name="Работа студента",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="improvements",
                        to="reviewers.review",
                        verbose_name="Рецензия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Улучшение",
                "verbose_name_plural": "Улучшения",
                "ordering": ["improvement_number"],
            },
        ),
        migrations.AddIndex(
            model_name="lessonsubmission",
            index=models.Index(
                fields=["status", "-submitted_at"], name="courses_les_status_07b77b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonsubmission",
            index=models.Index(fields=["mentor", "status"], name="courses_les_mentor__7b73b0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="lessonsubmission",
            unique_together={("student", "lesson")},
        ),
        migrations.AddIndex(
            model_name="improvementstep",
            index=models.Index(
                fields=["submission", "order"], name="courses_imp_submiss_2e0d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "-reviewed_at"], name="reviewers_r_reviewe_e832e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["lesson_submission"], name="reviewers_r_lesson__e03ba9_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["status"], name="reviewers_r_status_546c9b_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewernotification",
            index=models.Index(
                fields=["reviewer", "-created_at"], name="reviewers_r_reviewe_8e9195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewernotification",
            index=models.Index(fields=["is_read"], name="reviewers_r_is_read_2906e2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="stepprogress",
            unique_together={("profile", "step")},
        ),
        migrations.AddIndex(
            model_name="studentimprovement",
            index=models.Index(
                fields=["lesson_submission", "improvement_number"],
                name="reviewers_s_lesson__3feb62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentimprovement",
            index=models.Index(fields=["review"], name="reviewers_s_review__5c9d14_idx"),
        ),
        migrations.AddIndex(
            model_name="studentimprovement",
            index=models.Index(fields=["is_completed"], name="reviewers_s_is_comp_fa9dd6_idx"),
        ),
        migrations.AddIndex(
            model_name="studentimprovement",
            index=models.Index(fields=["created_at"], name="reviewers_s_created_2635fc_idx"),
        ),
    ]
