# Generated by Django 5.2.3 on 2025-12-01 15:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('approved', 'Принята'), ('needs_work', 'Требуются доработки'), ('rejected', 'Отклонена')], default='approved', max_length=20, verbose_name='Статус проверки')),
                ('comments', models.TextField(help_text='Общие комментарии и рекомендации по работе', verbose_name='Комментарии проверяющего')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка работы')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Примерное время затраченное на проверку', verbose_name='Время проверки (мин)')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('lesson_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='courses.lessonsubmission')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='authentication.reviewer', verbose_name='Проверяющий')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_submission', 'Новая работа на проверку'), ('resubmission', 'Повторная отправка работы'), ('student_question', 'Вопрос от студента'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, help_text='URL для перехода к связанному объекту', max_length=500, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.reviewer')),
            ],
            options={
                'verbose_name': 'Уведомление ревьюера',
                'verbose_name_plural': 'Уведомления ревьюеров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentImprovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('improvement_number', models.PositiveIntegerField(default=1, verbose_name='Номер улучшения')),
                ('improvement_text', models.TextField(help_text='Что именно нужно исправить или улучшить', verbose_name='Описание улучшения')),
                ('is_completed', models.BooleanField(default=False, help_text='Отметка студента о выполнении', verbose_name='Выполнено')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='reviewers.review')),
            ],
            options={
                'verbose_name': 'Улучшение',
                'verbose_name_plural': 'Улучшения',
                'ordering': ['improvement_number'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-reviewed_at'], name='reviewers_r_reviewe_e832e0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['lesson_submission'], name='reviewers_r_lesson__e03ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='reviewers_r_status_546c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewernotification',
            index=models.Index(fields=['reviewer', '-created_at'], name='reviewers_r_reviewe_8e9195_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewernotification',
            index=models.Index(fields=['is_read'], name='reviewers_r_is_read_2906e2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentimprovement',
            index=models.Index(fields=['review', 'improvement_number'], name='reviewers_s_review__ab9e30_idx'),
        ),
        migrations.AddIndex(
            model_name='studentimprovement',
            index=models.Index(fields=['is_completed'], name='reviewers_s_is_comp_fa9dd6_idx'),
        ),
    ]
