# Generated by Django 5.2.3 on 2026-01-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviewers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
    ]
