# Generated by Django 5.2.3 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentimprovement',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', help_text='Важность данного улучшения', max_length=10, verbose_name='Приоритет'),
        ),
    ]
