# Generated by Django 5.2.3 on 2025-12-02 20:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_reviewer_max_reviews_per_day'),
        ('courses', '0002_alter_lessonsubmission_unique_together_and_more'),
        ('reviewers', '0002_studentimprovement_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_url', models.URLField(verbose_name='Ссылка на работу')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('in_review', 'На проверке'), ('changes_requested', 'Требуются доработки'), ('approved', 'Одобрено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('mentor_comment', models.TextField(blank=True, help_text='Комментарий для студента о необходимых правках (поддерживает Markdown)', verbose_name='Комментарий ментора')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Когда ментор проверил работу', null=True, verbose_name='Дата проверки')),
                ('revision_count', models.IntegerField(default=0, help_text='Сколько раз работа отправлялась на доработку', verbose_name='Попытка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.lesson', verbose_name='Урок')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='authentication.student', verbose_name='Ментор')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_submissions', to='authentication.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Работа студента',
                'verbose_name_plural': 'Работы студентов',
                'db_table': 'courses_lessonsubmission',
            },
        ),
        migrations.CreateModel(
            name='ImprovementStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое описание того, что нужно исправить', max_length=300, verbose_name='Название шага')),
                ('description', models.TextField(help_text='Подробная инструкция для студента (поддерживает Markdown)', verbose_name='Описание')),
                ('order', models.IntegerField(default=0, help_text='Порядковый номер шага', verbose_name='Порядок')),
                ('is_completed', models.BooleanField(default=False, help_text='Студент отметил шаг как выполненный', verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_steps_list', to='reviewers.lessonsubmission', verbose_name='Работа студента')),
            ],
            options={
                'verbose_name': 'Шаг доработки',
                'verbose_name_plural': 'Шаги доработки',
                'db_table': 'courses_improvementstep',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='lesson_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviewers.lessonsubmission'),
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='authentication.student')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.step')),
            ],
            options={
                'verbose_name': 'Прогресс по шагу',
                'verbose_name_plural': 'Прогресс по шагам',
                'db_table': 'courses_stepprogress',
            },
        ),
        migrations.AddIndex(
            model_name='lessonsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='courses_les_status_07b77b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsubmission',
            index=models.Index(fields=['mentor', 'status'], name='courses_les_mentor__7b73b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonsubmission',
            unique_together={('student', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='improvementstep',
            index=models.Index(fields=['submission', 'order'], name='courses_imp_submiss_2e0d00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stepprogress',
            unique_together={('profile', 'step')},
        ),
    ]
