# Generated by Django 5.2.3 on 2025-12-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0003_lessonsubmission_improvementstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentimprovement',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Краткое название шага улучшения', max_length=200, verbose_name='Название улучшения'),
        ),
    ]
