# Generated by Django 5.2.3 on 2025-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0004_studentimprovement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('changes_requested', 'Требуются доработки'), ('approved', 'Одобрено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
