# Generated by Django 5.2.3 on 2025-12-08 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0005_alter_lessonsubmission_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentimprovement',
            name='reviewers_s_review__ab9e30_idx',
        ),
        migrations.RemoveField(
            model_name='studentimprovement',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='studentimprovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='studentimprovement',
            name='lesson_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='reviewers.lessonsubmission', verbose_name='Работа студента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('approved', 'Принята'), ('needs_work', 'Требуются доработки')], default='approved', max_length=20, verbose_name='Статус проверки'),
        ),
        migrations.AlterField(
            model_name='studentimprovement',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Когда студент отметил как выполненное', null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='studentimprovement',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvements', to='reviewers.review', verbose_name='Рецензия'),
        ),
        migrations.AddIndex(
            model_name='studentimprovement',
            index=models.Index(fields=['lesson_submission', 'improvement_number'], name='reviewers_s_lesson__3feb62_idx'),
        ),
        migrations.AddIndex(
            model_name='studentimprovement',
            index=models.Index(fields=['review'], name='reviewers_s_review__5c9d14_idx'),
        ),
        migrations.AddIndex(
            model_name='studentimprovement',
            index=models.Index(fields=['created_at'], name='reviewers_s_created_2635fc_idx'),
        ),
    ]
