# Generated by Django 5.2.3 on 2025-12-11 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0006_remove_studentimprovement_reviewers_s_review__ab9e30_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проверки'),
        ),
    ]
