# Generated by Django 5.2.3 on 2025-12-01 15:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории (макс. 100 символов)', max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия', max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Краткое описание категории', verbose_name='Описание')),
                ('icon', models.CharField(default='📝', help_text='Эмодзи или CSS класс для иконки', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#3498db', help_text='Цвет категории в формате HEX (#ffffff)', max_length=7, verbose_name='Цвет')),
                ('tag_keywords', models.TextField(blank=True, help_text='Ключевые слова для фильтрации тегов через запятую (например: python, basics, oop)', verbose_name='Ключевые слова для тегов')),
                ('badge', models.CharField(blank=True, help_text='Краткая метка для страницы тегов (например: Основы, Backend)', max_length=50, verbose_name='Бейдж')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке (0 - не показывать)', verbose_name='Порядок на странице тегов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email адрес для подписки', max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, help_text='Имя подписчика', max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная подписка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписан')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи (10-200 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из заголовка', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('subtitle', models.CharField(blank=True, help_text='Краткое описание статьи', max_length=300, verbose_name='Подзаголовок')),
                ('content', models.TextField(help_text='Основной текст статьи', validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, help_text='Краткое описание для предварительного просмотра', max_length=500, verbose_name='Краткое содержание')),
                ('featured_image', models.ImageField(blank=True, help_text='Изображение для обложки статьи', null=True, upload_to='blog/featured/', verbose_name='Главное изображение')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Описание изображения для SEO', max_length=200, verbose_name='Alt текст для изображения')),
                ('series_order', models.PositiveIntegerField(blank=True, help_text='Порядковый номер статьи в серии', null=True, verbose_name='Порядок в серии')),
                ('difficulty', models.CharField(choices=[('beginner', 'Новичок'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксpert')], default='beginner', max_length=20, verbose_name='Уровень сложности')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('meta_description', models.CharField(blank=True, help_text='Описание для поисковых систем (макс. 160 символов)', max_length=160, verbose_name='Meta описание')),
                ('meta_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=200, verbose_name='Ключевые слова')),
                ('og_title', models.CharField(blank=True, help_text='Заголовок для социальных сетей (по умолчанию = title)', max_length=100, verbose_name='OG заголовок')),
                ('og_description', models.CharField(blank=True, help_text='Описание для социальных сетей', max_length=200, verbose_name='OG описание')),
                ('og_image', models.ImageField(blank=True, help_text='Изображение для социальных сетей (1200x630px)', null=True, upload_to='blog/og/', verbose_name='OG изображение')),
                ('schema_type', models.CharField(default='Article', help_text='Тип структурированных данных', max_length=50, verbose_name='Тип Schema.org')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Примерное время чтения в минутах', verbose_name='Время чтения (мин)')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображается в блоке рекомендуемых статей', verbose_name='Рекомендуемая статья')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор (пользователь)')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Теги для статьи, разделенные запятыми', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('spam', 'Спам'), ('inappropriate', 'Неподходящий контент'), ('misinformation', 'Дезинформация'), ('copyright', 'Нарушение авторских прав'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип жалобы')),
                ('reason', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('reviewed', 'Рассмотрена'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата жалобы')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.article', verbose_name='Статья')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_reports', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Жалоба на статью',
                'verbose_name_plural': 'Жалобы на статьи',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Источник перехода')),
                ('time_on_page', models.PositiveIntegerField(default=0, verbose_name='Время на странице (сек)')),
                ('scroll_depth', models.PositiveIntegerField(default=0, verbose_name='Глубина прокрутки (%)')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('is_unique', models.BooleanField(default=True, help_text='Первый просмотр статьи этим пользователем/IP', verbose_name='Уникальный просмотр')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_views', to='blog.article', verbose_name='Статья')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр статьи',
                'verbose_name_plural': 'Просмотры статей',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Имя, которое будет показано в статьях', max_length=100, verbose_name='Отображаемое имя')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес профиля')),
                ('bio', models.TextField(help_text='Краткая биография автора', verbose_name='Биография')),
                ('specializations', models.CharField(blank=True, help_text='Области экспертизы, разделенные запятыми', max_length=200, verbose_name='Специализации')),
                ('job_title', models.CharField(blank=True, help_text='Текущая должность или звание', max_length=100, verbose_name='Должность')),
                ('company', models.CharField(blank=True, help_text='Место работы', max_length=100, verbose_name='Компания')),
                ('avatar', models.ImageField(blank=True, help_text='Фото автора (рекомендуется 300x300px)', null=True, upload_to='blog/authors/', verbose_name='Аватар')),
                ('cover_image', models.ImageField(blank=True, help_text='Изображение для шапки профиля (рекомендуется 1200x400px)', null=True, upload_to='blog/authors/covers/', verbose_name='Обложка профиля')),
                ('website', models.URLField(blank=True, verbose_name='Личный сайт')),
                ('twitter', models.CharField(blank=True, help_text='Имя пользователя без @', max_length=50, verbose_name='Twitter')),
                ('github', models.CharField(blank=True, help_text='Имя пользователя GitHub', max_length=50, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube канал')),
                ('telegram', models.CharField(blank=True, help_text='Имя пользователя без @', max_length=50, verbose_name='Telegram')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображается в блоке популярных авторов', verbose_name='Рекомендуемый автор')),
                ('show_email', models.BooleanField(default=False, help_text='Отображать email в публичном профиле', verbose_name='Показывать email')),
                ('accept_guest_posts', models.BooleanField(default=False, help_text='Готов рассматривать предложения о гостевых публикациях', verbose_name='Принимает гостевые посты')),
                ('articles_count', models.PositiveIntegerField(default=0, verbose_name='Количество статей')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Общие просмотры')),
                ('total_reactions', models.PositiveIntegerField(default=0, verbose_name='Общие реакции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автор блога',
                'verbose_name_plural': 'Авторы блога',
                'ordering': ['-articles_count', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='blog_author',
            field=models.ForeignKey(blank=True, help_text='Расширенный профиль автора (если создан)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.author', verbose_name='Профиль автора блога'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Содержание комментария', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_approved', models.BooleanField(default=True, help_text='Отображается ли комментарий на сайте', verbose_name='Одобрен')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название серии статей', max_length=200, verbose_name='Название серии')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес серии')),
                ('description', models.TextField(help_text='Краткое описание того, о чем серия статей', verbose_name='Описание серии')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/series/', verbose_name='Обложка серии')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершена'), ('paused', 'Приостановлена')], default='active', max_length=20, verbose_name='Статус серии')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображать в блоке рекомендуемых серий', verbose_name='Рекомендуемая серия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_series', to=settings.AUTH_USER_MODEL, verbose_name='Автор серии')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Теги для категоризации серии', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Серия статей',
                'verbose_name_plural': 'Серии статей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Серия, к которой принадлежит статья', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.series', verbose_name='Серия статей'),
        ),
        migrations.CreateModel(
            name='ArticleReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍 Нравится'), ('love', '❤️ Супер'), ('helpful', '💡 Полезно'), ('insightful', '🤔 Интересно'), ('amazing', '🤩 Потрясающе')], max_length=20, verbose_name='Тип реакции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на статью',
                'verbose_name_plural': 'Реакции на статьи',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Личные заметки пользователя к статье', verbose_name='Заметки')),
                ('folder', models.CharField(blank=True, help_text='Папка для группировки закладок', max_length=100, verbose_name='Папка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Прогресс чтения (%)')),
                ('reading_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Время чтения (сек)')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Прочитано')], default='not_started', max_length=20, verbose_name='Статус чтения')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='blog.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс чтения',
                'verbose_name_plural': 'Прогрессы чтения',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='blog_articl_status_8b18ca_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='blog_articl_categor_ff847e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', 'status'], name='blog_articl_is_feat_e2453a_idx'),
        ),
    ]
