# Generated by Django 5.2.3 on 2026-01-27 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_old_newsletters(apps, schema_editor):
    """Удаляем старые подписки без связи с пользователем"""
    Newsletter = apps.get_model("blog", "Newsletter")
    Newsletter.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Сначала удаляем все старые записи
        migrations.RunPython(delete_old_newsletters, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="newsletter",
            name="user",
            field=models.OneToOneField(
                help_text="Пользователь с подпиской на рассылку",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter_subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(
                help_text="Email адрес для подписки", max_length=254, verbose_name="Email"
            ),
        ),
    ]
