# Generated by Django 5.2.3 on 2026-01-27 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_newsletter_user_alter_newsletter_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(
                help_text="Email адрес для подписки",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Пользователь с подпиской на рассылку",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter_subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
