# Generated by Django 5.2.3 on 2026-01-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_newsletter_email_alter_newsletter_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Newsletter",
        ),
    ]
