# Generated by Django 5.2.3 on 2025-12-01 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('email', models.CharField(db_index=True, max_length=200, verbose_name='Email адрес')),
                ('topic', models.CharField(blank=True, choices=[('courses', 'Вопросы о курсах'), ('career', 'Карьерная консультация'), ('technical', 'Техническая поддержка'), ('partnership', 'Сотрудничество'), ('other', 'Другое')], max_length=50, null=True, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Обработано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки администратора')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'feedback',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10, verbose_name='Уровень')),
                ('action_type', models.CharField(choices=[('USER_LOGIN', 'Вход пользователя'), ('USER_LOGOUT', 'Выход пользователя'), ('USER_REGISTERED', 'Регистрация пользователя'), ('USER_UPDATED', 'Обновление пользователя'), ('USER_DELETED', 'Удаление пользователя'), ('FEEDBACK_CREATED', 'Создание обращения'), ('FEEDBACK_UPDATED', 'Обновление обращения'), ('FEEDBACK_DELETED', 'Удаление обращения'), ('SETTINGS_UPDATED', 'Изменение настроек'), ('COURSE_CREATED', 'Создание курса'), ('COURSE_UPDATED', 'Обновление курса'), ('COURSE_DELETED', 'Удаление курса'), ('PAYMENT_PROCESSED', 'Обработка платежа'), ('ERROR_OCCURRED', 'Ошибка'), ('SECURITY_EVENT', 'Событие безопасности')], db_index=True, max_length=50, verbose_name='Тип действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=10, verbose_name='Тип значения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Настройка системы',
                'verbose_name_plural': 'Настройки системы',
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
    ]
