# Generated by Django 5.2.3 on 2026-01-31 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import certificates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_user_groups_user_user_permissions_alter_role_name"),
        ("courses", "0006_step_troubleshooting_help_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        help_text="Дата достижения 100% прогресса курса",
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        db_index=True,
                        default=certificates.models.generate_certificate_number,
                        help_text="Уникальный номер формата CERT-YYYYMMDD-XXXX",
                        max_length=50,
                        unique=True,
                        verbose_name="Номер сертификата",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный код для проверки подлинности",
                        max_length=12,
                        unique=True,
                        verbose_name="Код верификации",
                    ),
                ),
                (
                    "lessons_completed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество завершенных уроков",
                        verbose_name="Пройдено уроков",
                    ),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Общее количество уроков в курсе",
                        verbose_name="Всего уроков",
                    ),
                ),
                (
                    "assignments_submitted",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество отправленных на проверку заданий",
                        verbose_name="Сдано заданий",
                    ),
                ),
                (
                    "assignments_approved",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество одобренных заданий",
                        verbose_name="Одобрено заданий",
                    ),
                ),
                (
                    "reviews_received",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество полученных ревью от проверяющих",
                        verbose_name="Получено проверок",
                    ),
                ),
                (
                    "total_time_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Общее время, затраченное на курс",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Время обучения (часы)",
                    ),
                ),
                (
                    "final_grade",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Оценка от 0 до 100 (если применимо)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Итоговая оценка",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Сгенерированный PDF сертификат",
                        null=True,
                        upload_to="certificates/",
                        verbose_name="PDF файл",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Статус действительности сертификата",
                        verbose_name="Действителен",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда сертификат был отозван",
                        null=True,
                        verbose_name="Дата отзыва",
                    ),
                ),
                (
                    "revoke_reason",
                    models.TextField(
                        blank=True,
                        help_text="Почему сертификат был отозван",
                        verbose_name="Причина отзыва",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Когда сертификат был выдан",
                        verbose_name="Дата выдачи",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Курс, по которому выдан сертификат",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Студент, получивший сертификат",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="authentication.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "db_table": "certificates",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(fields=["-issued_at"], name="certificate_issued__95315b_idx"),
                    models.Index(
                        fields=["certificate_number"], name="certificate_certifi_1d3ba1_idx"
                    ),
                    models.Index(
                        fields=["verification_code"], name="certificate_verific_8df4b9_idx"
                    ),
                    models.Index(
                        fields=["student", "-issued_at"], name="certificate_student_c6d78c_idx"
                    ),
                    models.Index(
                        fields=["course", "-issued_at"], name="certificate_course__973fe3_idx"
                    ),
                    models.Index(fields=["is_valid"], name="certificate_is_vali_20dedb_idx"),
                ],
                "unique_together": {("student", "course")},
            },
        ),
    ]
