# Generated by Django 5.2.3 on 2025-12-18 08:28

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import authentication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertiseArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Python, Django, JavaScript, React и т.д.",
                        max_length=100,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание области экспертизы",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Область экспертизы",
                "verbose_name_plural": "Области экспертизы",
                "ordering": ["name"],
                "permissions": [("manage_expertise", "Может управлять областями экспертизы")],
                "indexes": [models.Index(fields=["name"], name="authenticat_name_bd7ef3_idx")],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("mentor", "Ментор"),
                            ("reviewer", "Ревьюер"),
                            ("manager", "Менеджер"),
                            ("admin", "Администратор"),
                            ("support", "Поддержка"),
                        ],
                        help_text="Название роли",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Описание роли")),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
                "ordering": ["name"],
                "permissions": [
                    ("assign_roles", "Может назначать роли пользователям"),
                    ("manage_roles", "Может создавать и изменять роли"),
                ],
                "indexes": [models.Index(fields=["name"], name="authenticat_name_9c4dde_idx")],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_is_verified", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        default=authentication.models.get_default_student_role,
                        help_text="Роль пользователя в системе (по умолчанию: student)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="authentication.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["-date_joined"],
                "permissions": [
                    ("view_user_details", "Может просматривать детали пользователей"),
                    ("manage_user_roles", "Может управлять ролями пользователей"),
                    ("verify_user_email", "Может верифицировать email пользователей"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Основной телефон",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                ("birthday", models.DateField(blank=True, help_text="Дата рождения", null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Мужской"), ("female", "Женский"), ("other", "Другой")],
                        help_text="Пол пользователя",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, help_text="Страна", max_length=2
                    ),
                ),
                ("city", models.CharField(blank=True, help_text="Город", max_length=100)),
                ("address", models.TextField(blank=True, help_text="Адрес")),
                ("bio", models.TextField(blank=True, help_text="О себе", null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, help_text="Аватар", null=True, upload_to="avatars/"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, help_text="Уведомления по email"),
                ),
                (
                    "course_updates",
                    models.BooleanField(default=True, help_text="Обновления курсов"),
                ),
                (
                    "lesson_reminders",
                    models.BooleanField(default=True, help_text="Напоминания о уроках"),
                ),
                (
                    "achievement_alerts",
                    models.BooleanField(default=True, help_text="Уведомления о достижениях"),
                ),
                (
                    "weekly_summary",
                    models.BooleanField(default=True, help_text="Еженедельная сводка"),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(default=False, help_text="Маркетинговые письма"),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Публичный"),
                            ("students", "Только студенты"),
                            ("private", "Приватный"),
                        ],
                        default="students",
                        help_text="Видимость профиля",
                        max_length=20,
                    ),
                ),
                (
                    "show_progress",
                    models.BooleanField(default=True, help_text="Показывать прогресс"),
                ),
                (
                    "show_achievements",
                    models.BooleanField(default=True, help_text="Показывать достижения"),
                ),
                (
                    "allow_messages",
                    models.BooleanField(default=True, help_text="Разрешить сообщения"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Может ли студент получать доступ к курсам и отправлять задания",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Дата создания профиля"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Дата последнего обновления"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Курсы пользователя",
                        related_name="student_enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_own_progress", "Может просматривать свой прогресс обучения"),
                    ("submit_assignments", "Может отправлять задания на проверку"),
                    ("view_course_materials", "Может просматривать материалы курсов"),
                    ("manage_own_profile", "Может управлять своим профилем"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее обновление"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Поддержка",
                "verbose_name_plural": "Поддержка",
                "ordering": ["-registered_at"],
                "permissions": [
                    ("handle_support_tickets", "Обработка обращений пользователей"),
                    ("resolve_user_issues", "Решение проблем пользователей"),
                    ("view_support_queue", "Просмотр очереди обращений"),
                    ("manage_tickets", "Управление тикетами поддержки"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее обновление"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
                "ordering": ["-registered_at"],
                "permissions": [
                    ("full_system_access", "Полный доступ ко всей системе"),
                    ("manage_all_data", "Управление всеми данными через Django Admin"),
                    ("configure_system", "Настройка системных параметров"),
                    ("manage_permissions", "Управление правами доступа"),
                ],
                "indexes": [
                    models.Index(fields=["user"], name="authenticat_user_id_439441_idx"),
                    models.Index(fields=["is_active"], name="authenticat_is_acti_a39689_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее обновление"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Менеджер",
                "verbose_name_plural": "Менеджеры",
                "ordering": ["-registered_at"],
                "permissions": [
                    ("access_dashboard", "Доступ к менеджерской панели управления"),
                    ("view_platform_stats", "Просмотр статистики платформы"),
                    ("manage_users", "Управление пользователями платформы"),
                    ("manage_feedback", "Управление обратной связью"),
                    ("view_system_logs", "Просмотр системных логов"),
                ],
                "indexes": [
                    models.Index(fields=["user"], name="authenticat_user_id_a2d3ca_idx"),
                    models.Index(fields=["is_active"], name="authenticat_is_acti_eee1a0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее обновление"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentors",
                        to="courses.course",
                        verbose_name="Курсы",
                    ),
                ),
                (
                    "expertise_areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentors",
                        to="authentication.expertisearea",
                        verbose_name="Области экспертизы",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ментор",
                "verbose_name_plural": "Менторы",
                "ordering": ["-registered_at"],
                "permissions": [
                    ("manage_courses", "Может управлять курсами"),
                    ("create_lessons", "Может создавать уроки"),
                    ("edit_course_content", "Может редактировать контент курсов"),
                    ("view_student_progress", "Может просматривать прогресс студентов"),
                    ("mentor_students", "Может менторить студентов"),
                ],
                "indexes": [
                    models.Index(fields=["user"], name="authenticat_user_id_e76f4f_idx"),
                    models.Index(fields=["is_active"], name="authenticat_is_acti_417a78_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Информация о проверяющем, опыт работы",
                        verbose_name="Биография",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Может ли проверяющий брать новые работы",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(default=0, verbose_name="Всего проверок"),
                ),
                (
                    "average_review_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Среднее время от получения работы до проверки",
                        max_digits=6,
                        verbose_name="Среднее время проверки (часы)",
                    ),
                ),
                (
                    "max_reviews_per_day",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Максимальное количество работ которые можно проверить за день",
                        verbose_name="Макс. проверок в день",
                    ),
                ),
                (
                    "notify_new_submissions",
                    models.BooleanField(
                        default=True,
                        help_text="Получать email когда студент отправляет работу на проверку",
                        verbose_name="Уведомления о новых работах",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее обновление"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Курсы, работы по которым может проверять этот ревьюер",
                        related_name="reviewers",
                        to="courses.course",
                        verbose_name="Курсы для проверки",
                    ),
                ),
                (
                    "expertise_areas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Python, Django, JavaScript и т.д.",
                        related_name="reviewers",
                        to="authentication.expertisearea",
                        verbose_name="Области экспертизы",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверяющий",
                "verbose_name_plural": "Проверяющие",
                "ordering": ["-registered_at"],
                "permissions": [
                    ("review_submissions", "Может проверять работы студентов"),
                    ("approve_submissions", "Может одобрять работы"),
                    ("reject_submissions", "Может отклонять работы с замечаниями"),
                    ("view_all_submissions", "Может просматривать все работы на проверку"),
                    ("manage_review_queue", "Может управлять очередью проверок"),
                ],
                "indexes": [
                    models.Index(fields=["user"], name="authenticat_user_id_12aa74_idx"),
                    models.Index(fields=["is_active"], name="authenticat_is_acti_1af2e5_idx"),
                    models.Index(fields=["-total_reviews"], name="authenticat_total_r_93bb71_idx"),
                    models.Index(
                        fields=["-average_review_time"], name="authenticat_average_04fcff_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="authenticat_email_d74434_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="authenticat_role_id_614f7a_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="authenticat_is_acti_099f68_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-date_joined"], name="authenticat_date_jo_3efbf3_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["user"], name="authenticat_user_id_572c7b_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["country"], name="authenticat_country_599a94_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["is_active"], name="authenticat_is_acti_e622c2_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["-created_at"], name="authenticat_created_2ba38a_idx"),
        ),
        migrations.AddIndex(
            model_name="support",
            index=models.Index(fields=["user"], name="authenticat_user_id_162ae2_idx"),
        ),
        migrations.AddIndex(
            model_name="support",
            index=models.Index(fields=["is_active"], name="authenticat_is_acti_e54fb8_idx"),
        ),
    ]
