# Generated by Django 5.2.3 on 2025-12-01 15:16

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='courses.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='expertise_areas',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='authentication.expertisearea', verbose_name='Области экспертизы'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Курсы, работы по которым может проверять этот ревьюер', related_name='reviewers', to='courses.course', verbose_name='Курсы для проверки'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='expertise_areas',
            field=models.ManyToManyField(blank=True, help_text='Python, Django, JavaScript и т.д.', related_name='reviewers', to='authentication.expertisearea', verbose_name='Области экспертизы'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='authenticat_name_9c4dde_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=authentication.models.get_default_student_role, help_text='Роль пользователя в системе (по умолчанию: student)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Курсы пользователя', related_name='student_enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['user'], name='authenticat_user_id_439441_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_a39689_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['user'], name='authenticat_user_id_a2d3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_eee1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['user'], name='authenticat_user_id_e76f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='mentor',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_417a78_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewer',
            index=models.Index(fields=['user'], name='authenticat_user_id_12aa74_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewer',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_1af2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewer',
            index=models.Index(fields=['-total_reviews'], name='authenticat_total_r_93bb71_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewer',
            index=models.Index(fields=['-average_review_time'], name='authenticat_average_04fcff_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_d74434_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='authenticat_role_id_614f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_099f68_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='authenticat_date_jo_3efbf3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user'], name='authenticat_user_id_572c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['country'], name='authenticat_country_599a94_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_e622c2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-created_at'], name='authenticat_created_2ba38a_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['user'], name='authenticat_user_id_162ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_e54fb8_idx'),
        ),
    ]
