# Generated by Django 5.2.3 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='max_reviews_per_day',
            field=models.PositiveIntegerField(default=10, help_text='Максимальное количество работ которые можно проверить за день', verbose_name='Макс. проверок в день'),
        ),
    ]
