# Generated by Django 5.2.3 on 2026-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_groups_user_user_permissions_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("student", "Студент"),
                    ("mentor", "Ментор"),
                    ("reviewer", "Ревьюер"),
                    ("manager", "Менеджер"),
                    ("support", "Поддержка"),
                ],
                default="student",
                help_text="Название роли",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
