# Generated by Django 5.2.3 on 2025-12-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_reviewer_max_reviews_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='notify_new_submissions',
            field=models.BooleanField(default=True, help_text='Получать email когда студент отправляет работу на проверку', verbose_name='Уведомления о новых работах'),
        ),
    ]
