# Generated by Django 5.2.3 on 2026-02-02 17:29

from django.db import migrations


def transfer_users_to_student(apps, schema_editor):
    """
    Переносит всех пользователей с ролями admin и support в роль student.
    Удаляет роли admin и support из базы данных.
    """
    User = apps.get_model("authentication", "User")
    Role = apps.get_model("authentication", "Role")
    Student = apps.get_model("authentication", "Student")

    # Получаем роли
    try:
        student_role = Role.objects.get(name="student")
    except Role.DoesNotExist:
        # Создаём роль student если её нет
        student_role = Role.objects.create(
            name="student",
            description="Студент - проходит курсы, изучает материалы, выполняет задания",
        )

    # Находим пользователей с ролями admin и support
    admin_users = User.objects.filter(role__name="admin")
    support_users = User.objects.filter(role__name="support")

    # Переносим пользователей в студенты
    for user in admin_users:
        user.role = student_role
        user.is_staff = False  # Убираем staff права у бывших админов
        user.save()
        # Создаём Student профиль если его нет
        Student.objects.get_or_create(user=user)
        print(f"Перенесён admin пользователь {user.email} → student")

    for user in support_users:
        user.role = student_role
        user.save()
        # Создаём Student профиль если его нет
        Student.objects.get_or_create(user=user)
        print(f"Перенесён support пользователь {user.email} → student")

    # Удаляем роли admin и support
    deleted_admin = Role.objects.filter(name="admin").delete()
    deleted_support = Role.objects.filter(name="support").delete()

    print(f"Удалено ролей: admin={deleted_admin[0]}, support={deleted_support[0]}")


def reverse_transfer(apps, schema_editor):
    """
    Обратная миграция невозможна, т.к. мы не знаем кто был admin/support.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_support_role"),
    ]

    operations = [
        migrations.RunPython(transfer_users_to_student, reverse_transfer),
    ]
